(function(){
  const bank=window.QUESTION_BANK||[];
  const state={filter:'all',studyMode:false,items:[],index:0,selected:new Set(),submitted:false,random:false,instant:true,stats:JSON.parse(localStorage.getItem('ai-quiz-stats')||'{}')};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const current=()=>state.items[state.index];
  function save(){localStorage.setItem('ai-quiz-stats',JSON.stringify(state.stats));updateSummary()}
  function updateSummary(){const vals=Object.values(state.stats), done=vals.length, good=vals.filter(v=>v.correct).length;$('#doneCount').textContent=done;$('#accuracy').textContent=done?Math.round(good/done*100)+'%':'--';$('#wrongCount').textContent=vals.filter(v=>!v.correct).length}
  function makeItems(){let list=bank.filter(q=>state.filter==='all'||q.type===state.filter||(state.filter==='wrong'&&state.stats[q.id]&&!state.stats[q.id].correct));if(state.random)list=[...list].sort(()=>Math.random()-.5);state.items=list;state.index=Math.min(state.index,list.length-1);if(state.index<0)state.index=0;state.selected=new Set();state.submitted=false;render()}
  function render(){const q=current();$('#allCount').textContent=bank.length;$('#singleCount').textContent=bank.filter(x=>x.type==='single').length;$('#multipleCount').textContent=bank.filter(x=>x.type==='multiple').length;$('#modeLabel').textContent=state.studyMode?'背题模式 · '+(state.filter==='all'?'全部题目':state.filter==='single'?'单选题':state.filter==='multiple'?'多选题':'错题重练'):(state.filter==='all'?'全部题目':state.filter==='single'?'单选题':state.filter==='multiple'?'多选题':'错题重练');const total=state.items.length;$('#progressText').textContent=total?`${state.index+1} / ${total}`:'0 / 0';$('#progressBar').style.width=total?((state.index+1)/total*100)+'%':'0%';$('#paletteMeta').textContent=`${state.items.filter(q=>state.stats[q.id]).length} / ${total}`;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode==='memorize'?state.studyMode:b.dataset.filter===state.filter&&!state.studyMode));$('#submitBtn').textContent=state.studyMode?'背题浏览':'提交答案';renderCard(q);renderPalette()}
  function renderCard(q){const card=$('#questionCard');if(!q){card.innerHTML='<div class="empty-state"><div><b>暂无错题</b><span>继续练习，错题会自动收录</span></div></div>';$('#submitBtn').disabled=true;$('#prevBtn').disabled=true;$('#nextBtn').disabled=true;return}$('#submitBtn').disabled=state.studyMode;$('#prevBtn').disabled=state.index===0;$('#nextBtn').disabled=state.index===state.items.length-1;const stat=state.stats[q.id];const answered=state.submitted;const reveal=state.studyMode||answered&&state.instant;card.innerHTML=`<div class="question-meta"><span class="q-index">第 ${q.number} 题</span><span class="type-tag">${q.type==='single'?'单选题':'多选题'}</span></div><h2 class="question-title">${esc(q.question)}</h2><div class="options">${q.options.map(o=>{const sel=state.selected.has(o.key), right=reveal&&q.answer.includes(o.key), bad=reveal&&sel&&!right;return `<label class="option ${sel?'selected':''} ${right?'correct':''} ${bad?'incorrect':''}"><input type="checkbox" data-key="${o.key}" ${sel?'checked':''} ${state.studyMode||answered?'disabled':''}><span class="option-key">${o.key}</span><span class="option-text">${esc(o.text)}</span></label>`}).join('')}</div>${reveal?`<div class="result-note ${stat&&!stat.correct?'error':''}"><strong>${state.studyMode?'正确答案':(stat&&stat.correct?'回答正确':'回答错误')}</strong><span> · 正确答案：${q.answer.join('、')}</span></div>`:''}`;if(!answered&&!state.studyMode)card.querySelectorAll('.option').forEach(el=>el.addEventListener('click',()=>{const key=el.querySelector('input').dataset.key;if(q.type==='single')state.selected=new Set([key]);else state.selected.has(key)?state.selected.delete(key):state.selected.add(key);renderCard(q)}))}
  function renderPalette(){const p=$('#palette');p.innerHTML=state.items.map((q,i)=>{const s=state.stats[q.id],cl=i===state.index?'current':s?(s.correct?'done':'wrong'):'';return `<button class="${cl}" data-i="${i}">${i+1}</button>`}).join('');p.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.index=+b.dataset.i;state.selected=new Set();state.submitted=false;render()})}
  function submit(){const q=current();if(!q||state.studyMode||state.submitted)return;if(!state.selected.size){$('#questionCard').animate([{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],220);return}const correct=q.answer.length===state.selected.size&&q.answer.every(x=>state.selected.has(x));state.stats[q.id]={correct,at:Date.now()};state.submitted=true;save();render()}
  $('#submitBtn').onclick=submit;$('#prevBtn').onclick=()=>{if(state.index>0){state.index--;state.selected=new Set();state.submitted=false;render()}};$('#nextBtn').onclick=()=>{if(state.index<state.items.length-1){state.index++;state.selected=new Set();state.submitted=false;render()}};document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{if(b.dataset.mode==='memorize'){state.studyMode=true;state.index=0;makeItems();return}state.studyMode=false;state.filter=b.dataset.filter;state.index=0;makeItems()});$('#randomToggle').onchange=e=>{state.random=e.target.checked;state.index=0;makeItems()};$('#instantToggle').onchange=e=>{state.instant=e.target.checked};$('#resetBtn').onclick=()=>{if(confirm('确定清空本地答题记录吗？')){state.stats={};save();makeItems()}};document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')$('#prevBtn').click();if(e.key==='ArrowRight')$('#nextBtn').click();if(e.key==='Enter')submit()});updateSummary();makeItems();
})();
