(function () {
  const bank = window.QUESTION_BANK || [];
  const state = { source: 'all', filter: 'all', studyMode: false, items: [], index: 0, selected: new Set(), submitted: false, random: false, instant: true, stats: JSON.parse(localStorage.getItem('ai-quiz-stats') || '{}') };
  const $ = (s) => document.querySelector(s);
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const current = () => state.items[state.index];
  const typeName = (type) => ({ single: '单选题', multiple: '多选题', judge: '判断题' }[type] || type);
  const sourceName = (source) => ({ all: '全部题目', sample: '样题题库', network: '网络题库' }[source] || source);
  function save() { localStorage.setItem('ai-quiz-stats', JSON.stringify(state.stats)); updateSummary(); }
  function updateSummary() { const vals = Object.values(state.stats), done = vals.length, good = vals.filter((v) => v.correct).length; $('#doneCount').textContent = done; $('#accuracy').textContent = done ? Math.round(good / done * 100) + '%' : '--'; $('#wrongCount').textContent = vals.filter((v) => !v.correct).length; }
  function makeItems() { let list = bank.filter((q) => { const sourceOk = state.source === 'all' || q.source === state.source; const filterOk = state.filter === 'all' || q.type === state.filter || (state.filter === 'wrong' && state.stats[q.id] && !state.stats[q.id].correct); return sourceOk && filterOk; }); if (state.random) list = [...list].sort(() => Math.random() - 0.5); state.items = list; state.index = Math.min(Math.max(state.index, 0), Math.max(list.length - 1, 0)); state.selected = new Set(); state.submitted = false; render(); }
  function render() { const q = current(), total = state.items.length; $('#allCount').textContent = bank.length; $('#sampleCount').textContent = bank.filter((x) => x.source === 'sample').length; $('#networkCount').textContent = bank.filter((x) => x.source === 'network').length; $('#singleCount').textContent = bank.filter((x) => x.type === 'single').length; $('#multipleCount').textContent = bank.filter((x) => x.type === 'multiple').length; $('#judgeCount').textContent = bank.filter((x) => x.type === 'judge').length; $('#modeLabel').textContent = state.studyMode ? `背题模式 · ${sourceName(state.source)} · ${state.filter === 'all' ? '全部题型' : typeName(state.filter)}` : `${sourceName(state.source)}${state.filter === 'all' ? '' : ' · ' + (state.filter === 'wrong' ? '错题重练' : typeName(state.filter))}`; $('#progressText').textContent = total ? `${state.index + 1} / ${total}` : '0 / 0'; $('#progressBar').style.width = total ? ((state.index + 1) / total * 100) + '%' : '0%'; $('#paletteMeta').textContent = `${state.items.filter((item) => state.stats[item.id]).length} / ${total}`; document.querySelectorAll('.nav-btn').forEach((b) => b.classList.toggle('active', b.dataset.mode === 'memorize' ? state.studyMode : (b.dataset.source ? b.dataset.source === state.source && !state.studyMode : b.dataset.filter === state.filter && !state.studyMode))); renderCard(q); renderPalette(); }
  function renderCard(q) { const card = $('#questionCard'); if (!q) { card.innerHTML = '<div class="empty-state"><div><b>暂无题目</b><span>当前筛选条件下没有可显示的题目</span></div></div>'; $('#prevBtn').disabled = true; $('#nextBtn').disabled = true; return; } $('#prevBtn').disabled = state.index === 0; $('#nextBtn').disabled = state.index === state.items.length - 1; const stat = state.stats[q.id], answered = state.submitted, reveal = state.studyMode || (answered && state.instant), singleChoice = q.type !== 'multiple'; card.innerHTML = `<div class="question-meta"><span class="q-index">第 ${q.number} 题</span><span class="type-tag">${q.typeLabel || typeName(q.type)}</span><span class="type-tag source-tag">${q.sourceLabel || sourceName(q.source)}</span></div><h2 class="question-title">${esc(q.question)}</h2><div class="options">${q.options.map((o) => { const sel = state.selected.has(o.key), right = reveal && q.answer.includes(o.key), bad = reveal && sel && !right; return `<label class="option ${sel ? 'selected' : ''} ${right ? 'correct' : ''} ${bad ? 'incorrect' : ''}"><input type="checkbox" data-key="${o.key}" ${sel ? 'checked' : ''} ${state.studyMode || answered ? 'disabled' : ''}><span class="option-key">${o.key}</span><span class="option-text">${esc(o.text)}</span></label>`; }).join('')}</div>${reveal ? `<div class="result-note ${stat && !stat.correct ? 'error' : ''}"><strong>${state.studyMode ? '正确答案' : (stat && stat.correct ? '回答正确' : '回答错误')}</strong><span> · 正确答案：${q.answer.join('、')}</span></div>` : ''}`; if (!answered && !state.studyMode) card.querySelectorAll('.option').forEach((el) => el.addEventListener('click', () => { const key = el.querySelector('input').dataset.key; if (singleChoice) { state.selected = new Set([key]); finalizeCurrent(); render(); } else { state.selected.has(key) ? state.selected.delete(key) : state.selected.add(key); renderCard(q); } })); }
  function finalizeCurrent() { const q = current(); if (!q || state.studyMode || state.submitted || !state.selected.size) return false; const correct = q.answer.length === state.selected.size && q.answer.every((x) => state.selected.has(x)); state.stats[q.id] = { correct, at: Date.now() }; state.submitted = true; save(); return true; }
  function renderPalette() { const p = $('#palette'); p.innerHTML = state.items.map((q, i) => { const s = state.stats[q.id], cl = i === state.index ? 'current' : s ? (s.correct ? 'done' : 'wrong') : ''; return `<button class="${cl}" data-i="${i}">${i + 1}</button>`; }).join(''); p.querySelectorAll('button').forEach((b) => b.onclick = () => { finalizeCurrent(); state.index = +b.dataset.i; state.selected = new Set(); state.submitted = false; render(); }); }
  $('#prevBtn').onclick = () => { if (state.index > 0) { finalizeCurrent(); state.index--; state.selected = new Set(); state.submitted = false; render(); } }; $('#nextBtn').onclick = () => { if (state.index < state.items.length - 1) { finalizeCurrent(); state.index++; state.selected = new Set(); state.submitted = false; render(); } };
  document.querySelectorAll('.nav-btn').forEach((b) => b.onclick = () => { finalizeCurrent(); if (b.dataset.mode === 'memorize') { state.studyMode = true; state.index = 0; makeItems(); return; } state.studyMode = false; if (b.dataset.source) { state.source = b.dataset.source; state.filter = 'all'; } else { state.filter = b.dataset.filter; } state.index = 0; makeItems(); });
  $('#randomToggle').onchange = (e) => { state.random = e.target.checked; state.index = 0; makeItems(); }; $('#instantToggle').onchange = (e) => { state.instant = e.target.checked; if (state.submitted) render(); }; $('#resetBtn').onclick = () => { if (confirm('确定清空本地答题记录吗？')) { state.stats = {}; save(); makeItems(); } }; document.addEventListener('keydown', (e) => { if (e.key === 'ArrowLeft') $('#prevBtn').click(); if (e.key === 'ArrowRight') $('#nextBtn').click(); }); updateSummary(); makeItems();
})();
